### ISSUE TITLE
Next release TODO

### ISSUE THREAD

**Issue by machawk1** [machawk1/wail#286]
- [ ] Ensure consistency of functionality between macOS and Windows.
- [ ] Integrate latest version of OpenWayback (#266)
- [ ] Update README screenshot
