### ISSUE TITLE
Provide a DMG Blockmap file for releases 

### ISSUE THREAD

**Issue by machawk1** [machawk1/wail#418]
Some other open source tools (e.g., qri, https://github.com/qri-io/frontend/releases/) include a DMG blockmap file with releases. These provide checksums, among other things, so would be useful to include.

- [ ] Figure out the extent to what can be expressed in a DMG blockmap
- [ ] Figure out how to generate one
- [ ] Research the potential for usage for version diffs.

**Comment by machawk1** [comment]
Ping @b5 with the hope that he can provide some insight on how DMG blockmaps are useful for releasing macOS software using DMGs. :)

**Comment by b5** [comment]
Hey @machawk1! The `.blockmap` file is created as part of our publish process by [electron builder](https://github.com/electron-userland/electron-builder). the auto-update from that same suite of software uses the blockmap to resume downloads as needed.

I took a spin through the documentation & a quick look at the source, and couldn't find much in the way of documentation of the blockmap file (it's referred to as a "build artifact" in the docs), let alone how to generate one :/

**Comment by machawk1** [comment]
Thanks for the pointer and 2¢, @b5. Like most things on this project, I'll find a way to get one generating through some Python and bash-y duct taping. I suppose I'll document it if I find a programmatic way to do it beyond Electron.
